// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1789833228);
user_pref("app.update.lastUpdateTime.glean-addons-daily", 1789833228);
user_pref("app.update.lastUpdateTime.region-update-timer", 1789833228);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1789833228);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1789833228);
user_pref("browser.region.update.updated", 1789833199);
user_pref("browser.search.region", "EE");
user_pref("browser.termsofuse.prefMigrationCheck", true);
user_pref("calendar.alarms.ignored.legacyCleared", true);
user_pref("calendar.caldav.googleResync", 1789833198);
user_pref("calendar.list.sortOrder", "6f5addeb-32e0-41f6-986b-7dcd74adc09a 0b2e8484-991d-4f2f-8b79-d78b2595c619");
user_pref("calendar.registry.0b2e8484-991d-4f2f-8b79-d78b2595c619.calendar-main-default", true);
user_pref("calendar.registry.0b2e8484-991d-4f2f-8b79-d78b2595c619.calendar-main-in-composite", true);
user_pref("calendar.registry.0b2e8484-991d-4f2f-8b79-d78b2595c619.name", "personal-2026-09-19");
user_pref("calendar.registry.0b2e8484-991d-4f2f-8b79-d78b2595c619.type", "storage");
user_pref("calendar.registry.0b2e8484-991d-4f2f-8b79-d78b2595c619.uri", "moz-storage-calendar://");
user_pref("calendar.registry.6f5addeb-32e0-41f6-986b-7dcd74adc09a.calendar-main-in-composite", true);
user_pref("calendar.registry.6f5addeb-32e0-41f6-986b-7dcd74adc09a.disabled", true);
user_pref("calendar.registry.6f5addeb-32e0-41f6-986b-7dcd74adc09a.name", "Home");
user_pref("calendar.registry.6f5addeb-32e0-41f6-986b-7dcd74adc09a.type", "storage");
user_pref("calendar.registry.6f5addeb-32e0-41f6-986b-7dcd74adc09a.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Europe/Tallinn");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "c70a760f-e689-4036-85e3-4056d2abd28b");
user_pref("datareporting.dau.cachedUsageProfileID", "9cf9fdd8-1aa6-4cd6-892a-04bca33b2a5f");
user_pref("doh-rollout.home-region", "EE");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.cache.lastUpdate", 1789833228);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.hasExperimentsInstalled", false);
user_pref("extensions.hasExtensionsInstalled", false);
user_pref("extensions.lastAppBuildId", "20260910070223");
user_pref("extensions.lastAppVersion", "155.0.1");
user_pref("extensions.lastPlatformVersion", "155.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.tbpro-system-add-on@thunderbird.net", true);
user_pref("extensions.webextensions.uuids", "{\"tbpro-system-add-on@thunderbird.net\":\"189bdc9c-5e50-46d5-a381-5c3ed0530e26\",\"default-theme@mozilla.org\":\"7e507b5a-a98b-45aa-b364-6b9e328e5373\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1789834926);
user_pref("ldap_2.servers.history.uid", "e2fc57d3-e74d-43ac-ac9b-69edd6449010");
user_pref("ldap_2.servers.pab.uid", "00af3f20-9d49-434e-861b-50e1a9cfc06a");
user_pref("mail.root.imap", "/home/kiks/.config/thunderbird/xpfoqwxn.default-release/ImapMail");
user_pref("mail.root.imap-rel", "[ProfD]ImapMail");
user_pref("mail.root.pop3", "/home/kiks/.config/thunderbird/xpfoqwxn.default-release/Mail");
user_pref("mail.root.pop3-rel", "[ProfD]Mail");
user_pref("mail.ui-rdf.version", 62);
user_pref("mailnews.database.global.datastore.id", "4a6880df-890d-4ef2-9f31-0d37e8c1999");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.start_page_override.mstone", "155.0.1");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("network.cookie.validation.lastEpoch", 1);
user_pref("nimbus.profileId", "37866f11-f042-4372-b6f7-57aef41686e9");
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1789834926);
user_pref("print_printer", "Mozilla Save to PDF");
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("services.settings.clock_skew_seconds", -3162);
user_pref("services.settings.last_update_seconds", 1789836389);
user_pref("services.settings.thunderbird.hijack-blocklists.last_check", 1789836389);
user_pref("services.settings.thunderbird.url-classifier-skip-urls.last_check", 1789836389);
user_pref("signon.storage.rust.restoreDone", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1789834926);
user_pref("toolkit.profiles.newProfileSubmitted", true);
user_pref("toolkit.startup.last_success", 1789833197);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.cachedProfileGroupID", "decafdec-afde-cafd-ecaf-decafdecafde");
user_pref("toolkit.telemetry.previousBuildID", "20260910070223");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
